### ISSUE TITLE
Document 'Nacos monitor guide' has an error describe. Missing a blank.

### ISSUE THREAD

**Issue by gnosis-xian** [nacos-group/nacos-group.github.io#152]
When I config the prometheus. I find the document has a mistake.

The code area follow 'Nacos monitor guide - Deploy prometheus to collect Nacos metrics data' missing a blank. It may casue prometheus not startup.

```yaml
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets:['{ip1}:8848','{ip2}:8848','{ip3}:8848']
```
Change to:
```yaml
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets: ['{ip1}:8848','{ip2}:8848','{ip3}:8848']
```
